### ISSUE TITLE
[Analysis Request]: Indian Crime Analysis (Hacktoberfest '23)

### ISSUE THREAD

**Issue by sujanrupu** [developer-student-clubs/DataXchange#18]
### 📝 Description

** Describe the dataset and analysis requirements here:
I would like to add a machine learning data analysis script, which will analyse all the crimes in indian scenario according to past trends and other circumstances. It will analyse all the crimes state wise and time zone wise. 

### 📊 Dataset Details

**Dataset details here:
1. Major Dataset
    1.1. Crime by states
          1.1.1 Crime time
          1.1.2. Crime spot
           1.1.3 Victim details (Age, name, gender)
    1.2. Crime by districts

### 📈 Analysis Type

hacktoberfest

### 📂 Upload Dataset Files

[Data.zip](https://github.com/developer-student-clubs/DataXchange/files/12776251/Data.zip)

### I agree to and respect the Code of Conduct

- [X] I will also follow [CONTRIBUTING GUIDELINES](../blob/main/.github/CONTRIBUTING_GUIDELINE.md)

**Comment by rajatnai49** [comment]
Hello, @sujanrupu! Thanks for opening this issue!

**Comment by Chandak-Keshav** [comment]
Kindly assign me this @sujanrupu

**Comment by rajatnai49** [comment]
Goodbye, @rajatnai49! Thanks for your contributions and for closing this issue. If you have more questions or encounter other issues, feel free to reach out!
